-- phpMyAdmin SQL Dump
-- version 5.2.1
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Generation Time: Dec 08, 2023 at 07:50 AM
-- Server version: 10.4.28-MariaDB
-- PHP Version: 8.2.4

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `svpbdatabase`
--

-- --------------------------------------------------------

--
-- Table structure for table `categories`
--

CREATE TABLE `categories` (
  `category_id` int(11) NOT NULL,
  `name` varchar(255) NOT NULL,
  `user_id` int(11) DEFAULT NULL,
  `category_description` text DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Dumping data for table `categories`
--

INSERT INTO `categories` (`category_id`, `name`, `user_id`, `category_description`) VALUES
(63, 'Power Supplies (PSUs)', NULL, 'A power supply is a hardware component that converts electrical power from an outlet into the usable form required by a computer or electronic device. It provides a stable and regulated source of power to ensure the proper functioning of the components within the system.'),
(86, 'Central Processing Units (CPUs)', NULL, 'Central Processing Units (CPUs) are the primary components of a computer responsible for executing instructions and performing calculations, serving as the brain of the system by processing data and managing the overall operation of the computer.'),
(88, 'Motherboards', NULL, '\r\nMotherboards serve as the central circuitry hub in computers, providing connectivity and support for essential components such as the CPU, memory, and peripherals. They act as the backbone, facilitating communication between different hardware components to ensure a computer&#039;s functionality.'),
(103, ' Graphics Cards', NULL, 'Graphics cards, or GPUs, are hardware components integral to computers, responsible for rendering images and videos with speed and precision.'),
(104, 'Cooling Solutions', NULL, 'Cooling solutions refer to the methods and technologies employed to dissipate heat generated by electronic components, such as processors or graphics cards, within a computer system. '),
(107, 'Memory (RAM)', NULL, 'RAM, or Random Access Memory, is a type of volatile computer memory that provides high-speed data access to a processor and temporarily stores actively used data and machine code.');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `categories`
--
ALTER TABLE `categories`
  ADD PRIMARY KEY (`category_id`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `categories`
--
ALTER TABLE `categories`
  MODIFY `category_id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=114;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
